## Acknowledgements for each MacaqueNet research site

#### Affenberg Landskron
We are grateful to the entire Affenberg team for their support during our fieldwork period. We thank the managers of the Affenberg park, Peter and Svenja Gaubatz, for granting us access to the Japanese macaque population. Thanks to Dr. Bernard Wallner, Pia M. Böhm, Julia Herzele, and Markus Werdenig for their support and supervision during data collection. We are furthermore grateful for the research fellowship provided by Land Kärnten through Dr. Peter Kaiser.

#### Affenberg Salem
We are grateful to Ellen Merz and Roland Hilgartner for permission to conduct research and collect data at Affenberg Salem. We thank Lauren Cassidy, Tatjana Kaufmann and Lilah Sciaky for help with behavioural data collection. Data collection was funded by the Max Planck Society, the German Initiative of Excellence to the University of Göttingen and the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation)- Project number 254142454/GRK 2070.

#### Aghanashini Lion-Tailed Macaque Conservation Reserve
This work was carried out with financial support from the Department of Science and Technology of the Government of India (Grant No. SR/FT/LS-010/2007), Rufford Small Grants, Primate Conservation Inc. and CEPF-ATREE. 

#### Apenheul Primate Park
We are grateful to Lisette van den Berg for allowing us to conduct research at the Apenheul primate park. We thank all staff members and zookeepers who helped us during the study. We are grateful to Charlotte Kluiver for help with behavioural data collection. Data collection was funded by the European Union’s Horizon 2020 Marie Skłodowska-Curie Actions research and innovation program (grant number H2020-MSCA-IF-2019-893016 awarded to Debottam Bhattacharjee).

#### Artis Zoo
We are grateful to Karline Janmaat for allowing us to conduct research at the Artis Zoo. We thank all staff members and zookeepers who helped us during the study. We are grateful to Adam Zeeman for help with behavioural data collection. Data collection was funded by the European Union’s Horizon 2020 Marie Skłodowska-Curie Actions research and innovation program (grant number H2020-MSCA-IF-2019-893016 awarded to Debottam Bhattacharjee).

#### Bantimurung Bulusaraung National Park
We are grateful to the staff and the direction of the National Park for allowing us to conduct our research, to the Indonesian State Ministry of Research and Technology (RISTEK) for providing us research permits, to Victor Beltrán Francés for data collection and exceptional dedication to the protection of moor macaques, to Pak Jeki and Pak Nasri for valuable support during data collection, and to the German Research Foundation (DFG) for funding this project (research grant AM 409/4–1 to Dr. Federica Amici). We are grateful to Prof. Dr. Ngakan Putu Oka and Hasanuddin University for sponsoring our research. We thank Pak Haro and Hendra for their invaluable field assistance, Ibu Haji and Mama Aco for their hospitality, and San Diego State University for funding our work (President’s Leadership Fund and SDSU SEED grant to Erin Riley). We are also grateful to  Pak Iskandar Kamaruddin, Pak Dedy Asriady from BABULNP main office, for their friendship and support, Pak Amiruddin Dahlan and Pak Pado for their friendship and priceless field assistance, Dr. Isra Wahid (Universitas Hasanuddin) for scientific support and neverending joy, Ibu Madina and her children for warmly welcoming us in their home during the first years of the project, Cristina Sagnotti for brilliantly launching the project data collection, and the Italian Ministry of Education University and Research, and Roma Tre University for funding our work (MIUR, governmental program “Rientro dei Cervelli” D.M. 26/1/01 n.13 grant to Monica Carosi; Roma Tre University Doctoral Funding to Alessandro Albani and Lavinia Germani).

#### Batu Caves (same as Templer Park)
We would like to thank the Economi Planning Unit Malaysia, the Forestry Department of the Peninsular Malaysia and the Department of Wildlife and National Parks Peninsular Malaysia, Selangor for giving us permission to conduct our study. We are also grateful to Camille Luccisano, Eduardo Saczek, Silvia La Gala, Nur Atiqua Tahir, Shelby Samartino, and Rachael Hume for their assistance with data collection. We would like to also extend our gratitude to Nadine Ruppert and Ahmad Ismail for assisting with the logistics during field work. Data collection was supported by the National Science Foundation (#1518555) to Brenda McCowan.

#### Biomedical Primate Research Center of Rijswijk
We are grateful to the Biomedical Primate Research Center for allowing us to conduct our behavioural studies there, and in particular to Jan Langermans and Annet Louwerse. We thank our students, Essi Kaartinen, Fleur Hermanides, and Judith van der Loo, for their help in collecting data. Finally, we thank the animal keepers, Willem Ritter, Ruud Stas, and Alwin Blankestein, for their assistance with the monkeys. The behavioural studies on the rhesus macaques were supported by an Evolution and Behaviour grant from the Netherlands Organization for Scientific Research (NWO) to Elisabeth H.M. Sterck. 

#### Bioparco di Roma
We are grateful to the direction and staff of the Bioparco of Rome for allowing us to study their colony of Japanese macaques.

#### Blair Drummond Safari Park
We are grateful to Blair Drummond Safari Park for giving us permission to conduct our study with their group of Barbary macaques. We would like to thank Samir Clark, Sandra Rainey and Craig Holmes for their support and contribution to our research. Special thanks to research assistant Erin Morton for her invaluable help and assistance in data collection. This work was supported by the Natural Environment Research Council (NERC) through a PhD studentship administered by the IAPETUS Doctoral Training Partnership to Dr. Ivan Garcia-Nisa [Grant Number NE/L002590/1].

#### Blijdorp Zoo
We are grateful to Jos Hartog for allowing us to conduct research at the Blijdorp Zoo. We thank all staff members and zookeepers who helped us during the study. We thank Jolanda de Jong for help with behavioural data collection. Data collection was funded by the European Union’s Horizon 2020 Marie Skłodowska-Curie Actions research and innovation program (grant number H2020-MSCA-IF-2019-893016 awarded to Debottam Bhattacharjee).

#### Campbell Bay on Great Nicobar Island
The study on Nicobar long-tailed macaque project was funded by Science and Engineering Research Board- Department of Science and Technology, Government of India for the financial assistance to HNK (Grant No.SR/SO/AS-49/2011). The permit to conduct the study was given by Principal Chief Conservator of Forests, Port Blair, Andaman and Nicobar Islands (Permit No. CWLW/WL/134/566) and Assistant Commissioner, Andaman and Nicobar Administration to give access to the tribal areas. 

#### Cayo Santiago		
The Caribbean Primate Research Center, that manages Cayo Santiago, is supported by grant no. 2P40OD012217 from the National Center for Research Resources and the Office of Research Infrastructure Programs of the National Institutes of Health. Collection of behavioural data contributed to MacaqueNet was conducted by members of the Cayo Biobank Research Unit and funded by the National Institutes of Health [R01-AG060931, R01-MH-118203, R56AG071023, R01-MH096875, R01-MH089484], the Leverhulme Trust, and the European Research Council [FriendOrigins-864461]. We thank our dedicated team of research assistants and the University of Puerto Rico staff for their efforts.
				
#### Centre de Primatologie de l’Université de Strasbourg
We are grateful to the University of Strasbourg and Silabe (https://silabe.com/) for supporting this research and providing expert animal care. The behavioural study of rhesus, long-tailed and Tonkean macaques were funded by the University of Strasbourg Institute for Advanced Study (USIAS) as part of a USIAS fellowship to Dr. Hélène Meunier and by the ANR-21-CE37-0016 to Dr. Sébastien Ballesta.

#### Centro de Conservación Zoo Córdoba
We are grateful to the staff and the direction of the zoo in Córdoba for allowing us to conduct our research, to María Teresa Martínez Navarrete for data collection, and to the German Research Foundation (DFG) for funding this project (research grant AM 409/4–1 to Dr. Federica Amici).

#### Chamundi Temple
MISSING

#### Chester Zoo
We are grateful to the Chester Zoo Science Committee and Mammal Curators for granting permission for and facilitating this research. We are particularly thankful to the Chester Zoo Primate Team for their support during sample collection and the valuable time spent with researchers to help identify the macaques. Special appreciation also to Prof. Suzanne Shultz, University of Manchester, for her support and mentorship during this project. Research was internally funded by Chester Zoo.  

#### Coimbatore City
The study on bonnet macaques was funded by Science and Engineering Research board, J. C. Bose Fellowship to Prof. Mewa Singh. We thank the Tamil Nadu Forest Department for their support during the work. 

#### Ethology Station of Utrecht University
We are grateful to Elisbeth Sterck for allowing us to conduct research at the Ethology station. We thank Henk Westland for his assistance with the monkeys, Inge Luyten for helping with the data collection, and the animal caretakers of the Ethology station for their care for the monkeys.The behavioural studies on the long-tailed macaques were supported by an Evolution and Behaviour grant from the Netherlands Organization for Scientific Research (NWO) to Elisabeth H.M. Sterck. 

#### Ifrane National Park
We thank Ifrane National Park, the Haut Commissariat aux Eaux et Forêts et à la Lutte Contre la Désertification, Ecole Nationale Forestiere d'Ingénieurs and Institut Scientifique de Rabat for research permission and facilitation. Data collection was carried out under research permits #253/2013 (awarded to Prof Bonaventura Majolo, University of Lincoln, and Prof Mohamed Qarro, Ecole Nationale Forestière d’Ingénieurs), #44/2014 (awarded to Dr Patrick Tkaczynski, University of Roehampton, Prof Mohamed Mouna, Institut Scientifique de Rabat Project, and Els Van Lavieren, Morocco Primate Conservation).

#### Indira Gandhi Wildlife Sanctuary 
We thank Matthew Cooper for collecting and sharing the data collected in the Indira Gandhi Wildlife Sanctuary in Tamil Nadu, India. We also acknowledge that the sanctuary has since changed its name to the Anamalai Tiger Reserve. The research project was funded by a grant from the US National Science Foundation (grant number INT-9901439) to Matthew Cooper. The project received substantial support from Mewa Singh at Mysore University and the field site he established in the Anamalai Hills. Key members of Mewa Singh’s team that supported the project and field site include M.A. Anand, H.N. Kumara, A.K. Sharma, and H.S. Sushma. We also thank the Tamil Nadu Forest Department for permission to conduct research and Waterfall Tea Estates for logistical support. 
#### Instituto Nacional de Psiquiatría Ramón de la Fuente Muñiz
We are grateful to the INPRFM technical, scientific, and administrative staff for all the support provided to collect our behavioural observations during the 2004-2005 and 2007-2008 periods. Part of the study was funded by the National Council for Science and Technology (CONACYT) via the PhD scholarship 3000000,1 granted to Claudio de la O. 

#### Khao Yai National Park
We are grateful to the National Research Council of Thailand (NRCT) and the Department of National Parks, Wildlife and Plant Conservation (DNP) for granting permission to conduct research at Khao Yai National Park. We thank our collaborators Dr. Suchinda Malaivijitnond, Chulalongkorn University, Dr. Chanpen Saralamba, Mahidol University, and the superintendents of Khao Yai National Park for their cooperation and support over the years. International field assistants Corey Bither, Christopher Coll-Beswick, Nik Long, and Michelle Reed helped collecting data and maintaining the field site, for which we are deeply grateful. This research would not have been possible without financial support from the National Primate Research Center of Thailand and a Graduate and Professional Student Council Research Award of Southern Illinois University Carbondale.

#### Koshima Island
For all data on Koshima Island: We are grateful to the staff and researchers working at Koshima Island and at the Research station, to the Kyoto University's Wildlife Research Center, and to the city of Kushima's Agency for Cultural Affairs, for allowing us to conduct research, to Takafumi Suzumura and to Prof. Andrew MacIntosh for personal and logistic help.
For data provided by Duboscq, Sueur, Romano & MacIntosh: We thank the Department Ecology, Physiology, Ethology of the Institute Hubert Curien in Strasbourg and the University of Strasbourg Advanced Institute for providing ressources for this data collection.
For data provided by Amici: We are also grateful to Dr. Alba Castellano Navarro and Emilio Macanás Martínez for data collection and dedication, and Zhihong Xu for personal and logistic help on Koshima Island, and to the German Research Foundation (DFG) for funding this project (research grant AM 409/4–1 to Dr. Federica Amici).

#### Kuala Lumpur district
We are grateful to Dr. Karimullah Karimullah for data collection, to Prof. Shahrul Anuar Mohd Sah from Universiti Sains Malaysia for extensive support during data collection and for allowing us to conduct research, and to the German Research Foundation (DFG) for funding this project (research grant AM 409/4–1 to Dr. Federica Amici).

#### La Montagne des Singes
We are grateful to Ellen Merz, to the staff and the direction of La Montagne des Singes for allowing us to conduct our research, to María Teresa Martínez Navarrete for data collection, and to the German Research Foundation (DFG) for funding this project (research grant AM 409/4–1 to Dr. Federica Amici).

#### Laboratory of Comparative Ethology
Research at the Laboratory of Comparative Ethology (LCE) was supported by the Division of Intramural Research at the Eunice Kennedy Shriver National Institute of Child Health & Human Development (NICHD) at the National Institutes of Health.

#### Lore Lindu National Park
We thank the Indonesian Institute of Sciences (LIPI) and the Indonesian Ministry of Forestry (PHKA) for granting research permits, and Noviar Andayani and Amir Hamzah for their sponsorship. We are grateful to our outstanding field assistants who made this work possible (Manto, James, Papa Denis, Pak Asdi, Pias, Tinus, and Papa Tri) and the villages of Tomado, Anca, and Kalora for accepting us into their communities. We also thank the following organization for their financial support: the U.S. National Science Foundation, Wildlife Conservation Society, Wenner-Gren Foundation, and the American Society of Primatologists.

#### Marwell Zoo
We thank Tim Woodfine, Heidi Mitchell, Will Justice, Shelly Parkes, Kevin Saunders, Andy Double, John Pullen and all the keepers of the East section at Marwell Zoo for granting us access to the animals and for their assistance and enthusiasm throughout data collection. 

#### Mount Huangshan National Park
We thank the Huangshan Monkey Management Centre and the Huangshan Garden Forest Bureau for their permission to conduct research at the field site. We thank the following organizations for providing financial support: the Leakey Foundation, the Wenner-Gren Foundation and the National Geographic Society; National Natural Science Foundation of China (No. 32370533, 32370535, 32070455, 31971404), and the Anhui Provincial Natural Science Foundation (2108085Y12), Key Teacher Program of the Ministry of Education of China and the Excellent Youth Foundation of Anhui. We thank the late Prof. Qi-Shan Wang, Anhui University, who established the field site at the Valley of Wild Monkey in Fuxi village. We thank the following collaborators: Prof. Carol Berman, State University of New York, Prof. Paul A. Garber, University of Illinois, Prof. Randall C. Kyes, University of Washington, Prof. Lixing Sun and Lori K. Sheeran, Central Washington University for their cooperation and support in the macaque projects conducted at the site. Many thanks to all past, present and future research assistants and Ph.D./master students of the International Collaborative Research Center for Huangshan Biodiversity and Tibetan Macaque Behavioral Ecology, who have collected and contributed to this work. We are grateful to Lei Zhang and Akie Yanagi for translating Chinese and Japanese works into English, Xinming Chen and his family for providing housing and accommodation in China.

#### Nürnberg Zoo
We are grateful to the staff and the direction of the Nürnberg Zoo for allowing us to conduct our research, to María Teresa Martínez Navarrete for data collection, and to the German Research Foundation (DFG) for funding this project (research grant AM 409/4–1 to Dr. Federica Amici).

#### Parc Zoologique de Thoiry
We wish to thank the staff of Parc Zoologique de Thoiry (France) for assisting the work on site and helping in individual recognition of the subjects. We are also grateful to several students who contributed to the data collection.

#### Phu Khieo Wildlife Sanctuary
We are grateful to the National Research Council of Thailand (NRCT) and the Department of National Parks, Wildlife and Plant Conservation (DNP) for permission to conduct our research at the Phu Khieo Wildlife Sanctuary. We thank our collaborators, in particular Prof. Naris Bhumpakphan, Kasetsart University, Prof. Suchinda Malaivijitnond, Chulalongkorn University, and the respective superintendents of Phu Khieo Wildlife Sanctuary for their cooperation and support over the years. We thank Prof. A. Koenig and Dr. C. Borries, Stony Brook University, who established the field site at Mai Sot Yai. Our research would not be possible without the fantastic team of local assistants collecting data at Phu Khieo. Lastly, we acknowledge the support of the involved institutions and funding bodies that make our research possible.

#### Kyoto University Primate Research Institute
We thank the Monkey Ethic Committee of the KUPRI for allowing us to conduct research there, Zhihong Xu for help in data collection, and all the caretakers responsible for the macaques at KUPRI for their curiosity and engagement.

#### Sangeh Monkey Forest
We are grateful to the staff and the direction of the Sangeh Monkey Forest (Mr. I Made Mohon for allowing us to conduct our research, and to the Indonesian State Ministry of Research and Technology (RISTEK) for providing us research permits. For their scientific supervision and logistic support, we are grateful to Dr. Fany Brotcorne (ULiege) and Prof. I. Nengah Wandia (Udayana University). Data collection was supported by the Belgian National Fund for Scientific Research, the Fondation de Lille and the University of Paris 13.

#### Segari Melintang Forest Reserve
We thank the project’s field research coordinator Dr. Nurul Iza Adrina for managing the field site and research assistants, and the co-founders of the Macaca Nemestrina Project, Dr. Antje Engelhardt and Dr. Shahrul Anuar Mohd Sah for their ongoing support. We are deeply grateful to all local and international students, volunteers and field assistants of this project who have contributed to data collection throughout the years. We gratefully acknowledge the permission of the Forestry Department Perak, Department of Wildlife and National Parks Peninsular Malaysia, and Felcra Sdn. Bhd. to conduct research on wild southern pig-tailed macaques in the Segari Melintang Forest Reserve and surrounding oil palm plantations. We also thank the Malaysian Primatological Society for administrative support and our many funders, nongovernmental organisations, private donors, academic institutions, or governmental entities (https://primatesmalaysia.org/home/macaca-nemestrina-project/) who have been supportive of our work.

#### Shimla City
We are grateful to the Himachal Pradesh Forest Department for granting us permission to conduct our research in Shimla. We would like to thank Eduardo Saczek, Taniya Gill, Kawaljit Kaur, Bidisha Chakraborty, Benjamin Sipes, Nalina Aiempichitkijkarn for helping us with data collection as well as Lalit Mohan, Sandeep Rattan, and Santosh Thakur for helping us with the logistics. Data collection was supported by the National Science Foundation (#1518555) to Brenda McCowan. 

#### Tangkoko Batuangus Nature Reserve
We are grateful to Dr. Antje Engelhardt and Jan-Boje Pfeifer, founders and pillars of the MNP and to our long-term Indonesian partners, Dr. Muhammad Agil and Prof. Perwitasari-Farajallah. We gratefully acknowledge the permission of the Indonesian State Ministry of Research and Technology (RISTEK), the Directorate General of Forest Protection and Nature Conservation (PHKA) in Jakarta, and the Department for the Conservation of Natural Resources (BKSDA) in Manado to conduct research in the Tangkoko Nature Reserve. We also want to thank our many funders, nongovernmental organisations and agencies, private foundations, academic institutions, or governmental entities (https://macaca-nigra.org/). Finally, many thanks to all past, present and future Macaca Nigra Project members who have collected and contributed, do and will collect and contribute datasets for the MacaqueNet database.

#### Templer Park (same as Batu Caves)
We would like to thank the Economi Planning Unit Malaysia, the Forestry Department of the Peninsular Malaysia and the Department of Wildlife and National Parks Peninsular Malaysia, Selangor for giving us permission to conduct our study. We are also grateful to Camille Luccisano, Eduardo Saczek, Silvia La Gala, Nur Atiqua Tahir, Shelby Samartino, and Rachael Hume for their assistance with data collection. We would like to also extend our gratitude to Nadine Ruppert and Ahmad Ismail for assisting with the logistics during field work. Data collection was supported by the National Science Foundation (#1518555) to Brenda McCowan.

#### Thenmala
We would like to thank the Kerala Forest Department and the Indian Institute of Science Education and Research (IISER) Thiruvananthapuram for facilitating our research in Thenmala. We are grateful to Dr Hema Somanathan and her research group at IISER Thiruvananthapuram for providing access to their Field Station, and for assisting with logistics. Finally, we would like to thank Pooja Dongre, Mohammed Ismail, Megha Majoe, Rajarshi Saha, Alvaro Sobrino, and Menno Van Berkel for their assistance with data collection. This work was supported by the National Science Foundation (#1518555) to Brenda McCowan. 

#### Trentham Monkey Forest
We thank Trentham Monkey Forest for supporting our research and giving us permission to conduct our study with their Barbary macaque groups. We are particularly thankful to Mallory Owens for her assistance in data collection. This work was supported by a Royal Society Dorothy Hodgkin Fellowship to Professor Rachel L. Kendal., and the Natural Environment Research Council (NERC) through a PhD studentship administered by the IAPETUS Doctoral Training Partnership to Dr. Ivan Garcia-Nisa [Grant Number NE/L002590/1].

#### Tukeswari Temple 
We thank Matthew Cooper for collecting and sharing the data collected at Tukeswari Temple in Assam, India. The research project was funded by a grant from the National Geographic Society (grant number 5862) to Matthew Cooper and Irwin Bernstein. We are also grateful to the Indo-US Primate Project for supporting this project and the Assam Forest Department for permission to conduct the research. Other members of the Indo-US Primate Project supporting this research project include S.M. Mohnot, Charles Southwick, Arun Srivastava, and Prabal Sakar. 

#### Ubud Monkey Forest
We sincerely thank the Indonesian Ministry of Research and Technology, Mr. Sri Wahyono, the head of the Primate Research Center of Udayana University, Dr. I Nengah Wandia, the General Managers of the Monkey Forest Ubud, Mr. Nyoman Buana and Mr. Nyoman Sutarjana, and their team for allowing us to conduct this research in Indonesia and for their logistic support. We thank Dr. Fany Brotcorne and Dr. Marie-Claude Huynen for their scientific supervision. We are very grateful to Damien Broens, Sophie Delooz and Fanny de Thier Nagelmackers for their significant help in the behavioural data collection. This work was made possible with the financial support of the Belgian National Fund for Scientific Research (F.R.S.-FNRS, FRIA grant), the University of Liège Fundations (Modus Mobility grant, Fundations Docquier, Denise Dounan, Rolande Maréchal, Marie-Louise Léonard, Camille Hela, and Herman-van Beneden), the Erasmus+ program, and the Léopold III Foundation's funds for Nature Exploration and Conservation (IRScNB).

#### Uluwatu Temple
We are grateful to the Indonesian State Ministry of Research and Technology (RISTEK, Mr. Sri Wahyono), and the Uluwatu Temple management committee for permission to conduct this research in Indonesia. We are very grateful to Anna Holzner and Lucía Jorge Sales for their incredible support with behavioural data collection. This research was funded by the Natural Sciences and Engineering Research Council of Canada (Discovery Grant No. 2015-06034), the Alberta Gambling Research Institute (Major Grant No. G00003422), Arts and Science at the University of Lethbridge, the University of Lethbridge Research Fund (Grant No. G00002931); the Leopold III Fund for the Exploration and Conservation of Nature (Belgium) and the Belgian Federation of Graduated Women. 

#### Upper Rock Nature Reserve
We are grateful to Eric Shaw, the Helping Hand Trust and Gibraltar Ornithological and Natural History Society for allowing us to conduct our research, to Dr. Alvaro Lopez Caicoya and Dr. Veronika Roubova for data collection and remarkable endurance, and to the German Research Foundation (DFG) for funding this project (research grant AM 409/4–1 to Dr. Federica Amici). Independent project and data collection was supported by University of Vienna and University of South Bohemia under the collaboration between Dr. Martina Konecna and Dr. Bernard Wallner.

#### Wat Khuha Santayaram Monastery
MISSING

#### Yakushima Island
We thank the Yakushima District Forestry Office for permission to carry on the study. We are grateful to Dr. S. Suzuki, Dr. D.S. Hill and the students at the Kyoto University Yakushima Station who kindly helped us in many ways during the study.

#### Zoo de l’Orangerie
MISSING

#### ZooParc de Beauval
MISSING

#### RESEARCH SITES FOR WHICH CONTRIBUTED DATA HAS NOT YET BEEN FULLY CLEANED

#### Baluran National Park
We are beyond grateful to the management and staff of Taman Nasional Baluran (TNB), especially, Kepala Balai Ir. Bambang Sukendro and Ibu Arif Pratiwi, who from the beginning supported our research and our presence in TNB. The Indonesian Ministry of Research and Technology granted the permit for our research for which we truly thank them. We were also fortunate to have in-country support from the Directorate General of Natural Resource and Ecosystem Conservation, thank you tremendously. Thank you to Dr. Kanthi Arum Widayati from Institut Pertanian Bogor for supporting the research in-country as well. The TNB Copenhagen Zoo staff supported us greatly during the process, thank you to Pak Hariyawan Agung Wahyudi, Doktor Hewan Rudiar, Betty, Dani and of course, Pak Misro. We are forever grateful to the people of Wonorejo for their support and their willingness to include us in their community. The research was funded by Innovation Fund Denmark (project no. 5189-00135B) with support from the QATO Foundation, and supervised by Professor Torben Dabelsteen, Mikkel Stelvig and Dr. Carl Træholt. Thank you.

#### Ketambe Research Station
We thank the Indonesian Institute of Sciences (L.I.P.I.) and the Directorate of Nature Conservation (P.H.P.A.) for permission to work in the Ketambe Study Area and we thank Universitas Nasional in Jakarta (UNAS) for many years of collaboration and sponsoring of our fieldwork. CvS and MvN gratefully acknowledge the financial support of the Netherlands Foundation for the Advancement of Tropical Research (WOTRO).

#### La Forêt des Singes de Rocamadour
We are grateful to Ellen Merz, to the staff and the direction of La Forêt des Singes at Rocamadour for allowing us to conduct this research, to Eva-Maria Rathke and Magdalena Wimmer, Luisa Beckmann, Lateefah Roth, and Marie‐Laure Poiret for their help in collecting the data. Data collection was funded by the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation, project number 360742713 (Fi707/22‐1) and 254142454/GRK 2070). We further acknowledge support through a Seed fund by the Leibniz ScienceCampus Primate Cognition, funded by the Leibniz Association.
